### ISSUE TITLE
DHCP section hangs forever

### ISSUE THREAD

**Issue by cprivitere** [equinix-labs/terraform-equinix-metal-nutanix-cluster#58]
I've noticed an issue where the DHCP step of the deployment may hang forever with 0 IPs detected.

```
Waiting for at least 6 leases in /var/lib/misc/dnsmasq.leases, found 0...
```

**Workaround**
Log into the bastion host and run `systemctl restart dnsmasq`

We could try to code some additional starts to avoid whatever race is leading to dnsmasq not coming up after the bastion host's reboot.

**Comment by ctreatma** [comment]
#55 adds a timeout in the wait for DHCP script to at least partially resolve this.  Is there an additional check we could add there to restart dnsmasq if needed?

**Comment by displague** [comment]
There was some conversation that this could be related to the sequencing of network interface turn-up, package installation, and service start.

If `dnsmasq` is dependent on the `bond` device being up, which was suggested, https://manpages.ubuntu.com/manpages/noble/en/man5/interfaces.5.html offers `post-up` actions were `systemctl restart dnsmasq` could be applied.

**Comment by cprivitere** [comment]
I believe adding the restart of dnsmasq adequately addressed this.
