### ISSUE TITLE
examples: Connectivity to Active Directory

### ISSUE THREAD

**Issue by displague** [equinix-labs/terraform-equinix-metal-nutanix-cluster#67]
Create a new example, use the Nutanix module and any additional resources (Windows server running on Equinix Metal, or elsewhere) to attach Prism Central to Active Directory from from that Windows node, run within the same VLAN.  If this takes advantage of the bastion node's DHCP services, caution will need to be taken to ensure that the DHCP node count detection used to verify all Nutanix nodes are ready is not confused by a Windows node claiming address space.  This may not be a problem if Nutanix leases are safely detected.

Resources:
- https://deploy.equinix.com/developers/guides/windows-server-setup/ (also see the `cloudbase-init` documentation there)
- https://www.youtube.com/watch?v=VrX60ubP18Q

It may not be possible to automate all layers of setup. The example may create infrastructure that must be manually setup by following a guide in the example's README.md.

The example/README.md would take advantage of much of the same instruction provided in https://equinix-labs.github.io/nutanix-on-equinix-metal-workshop/. The instructions on setting up Prism Central would aid in configuring Nutanix to connect to the Windows AD node.

**Comment by displague** [comment]
Per our conversation yesterday, if Prism Central configuration can not be automated, it may be necessary to split the example into two phases or examples where pre-prism-central work is done and then post-prism-central work is done (depending on the information needed to connect to prism central).

Another alternative: 
- Use [PhantomJS/CasperJS/Selenium/etc](https://github.com/dhamaniasad/HeadlessBrowsers) from the bootstrap node (this assumes that browser based activation is the only approach, API is likely possible)

**Comment by aayushrangwala** [comment]
> Per our conversation yesterday, if Prism Central configuration can not be automated, it may be necessary to split the example into two phases or examples where pre-prism-central work is done and then post-prism-central work is done (where the second example is dependent on the variables needed to connect to prism central ).
> 
> (perhaps that could look like this)
> 
> ```hcl
> # example/with-windows-active-directory/main-variables-outputs.tf
> 
> variable "prism_central_configured" { default = false; description = "Set to true once Prism Central is enabled"}
> outputs "next_steps" { value = var.prism_central_configured ? "Enable Prism Central by doing ... then set prism_central_configured and terraform apply again" : "Try our other examples"}
> 
> module "nutanix" { ... }
> // extra provisioners
> 
> module "part2" {
> source = "./part2/"
> count = var.prism_central_configured ? 1:0
> ...
> }
> ```
> 
> Another alternative:
> 
> * Use [PhantomJS/CasperJS/Selenium/etc](https://github.com/dhamaniasad/HeadlessBrowsers) from the bootstrap node to enable Prism Central (this assumes that browser based activation is the only approach, API is likely possible)

yes @displague that makes sense. I'm trying to have a script, configuring these steps but if that doesnt work we can use this approach. I think if we have to have 2 phases of the examples, then workshop would make a better sense.
